### ISSUE TITLE
Can I load here vector tile through harp-leaflet?

### ISSUE THREAD

**Issue by kochizufan** [heremaps/harp-leaflet#2]
Hi 

I want to load here vector tile through harp-leaflet
https://developer.here.com/documentation/maps/topics/vector.html

Because I want to use here vector map in leaflet.

Is this possible?

**Comment by zbigg** [comment]
Sorry for late answer, but there is good news - it's possible. Unfortunately we don't have any good example / up-to-date guide and up to now it was quite complicated.

As this was requested via other channels too, I will create an example how this can be achieved with newly available, but in principle these are steps required to render HERE Vector Tile data:

1) Gathe proper credentials, doc is here: https://developer.here.com/documentation/vector-tiles-api/dev_guide/index.html

2) Use `UserAuth` helper from `@here/olp-sdk-authentication` as OAuth provider:
```
import { requestToken, UserAuth } from "@here/olp-sdk-authentication";
...
    const userAuth = new UserAuth({
        env: "here",
        credentials: {
            accessKeyId: "your-access-key-id",
            accessKeySecret: "your-access-key-secret"
        },
        tokenRequester: requestToken
    });
```
3) Pass this as constructor to `OmvDataSource`:
```
        baseUrl: "https://vector.hereapi.com/v2/vectortiles/base/mc",
        apiFormat: APIFormat.HereV1,
        authenticationCode: () => { return userAuth.getToken(); },
```

Wasn't able to test it directly, but https://github.com/heremaps/harp-leaflet/blob/master/examples/src/example_basic.ts adapted with changes above should allow you to render HERE Vector Tiles.
