### ISSUE TITLE
Upgrade mapView to 0.11.0

### ISSUE THREAD

**Issue by david-schopf** [heremaps/harp-leaflet#3]
This package is not compatible anymore with the newest mapView:
"@here/harp-mapview": "^0.11.0"

**Comment by skosmella** [comment]
Thank you for raising this. We are taking immediate actions to upgrade the leaflet plugin to harp 0.11.0

**Comment by zbigg** [comment]
The newly released, [0.2.0](https://www.npmjs.com/package/@here/harp-leaflet/v/0.2.0) version of this plugin is compatible with latest release of `harp.gl`.
